# Generated by Django 5.2.6 on 2025-12-30 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_name", models.CharField(max_length=100)),
                ("employee_email", models.EmailField(max_length=254, unique=True)),
                ("employee_phone", models.IntegerField(unique=True)),
                ("employee_address", models.TextField()),
                (
                    "employee_role",
                    models.IntegerField(choices=[(1, "מנהל"), (2, "עובד")]),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "team_Manager_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="TasksManagementApp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=100)),
                ("task_description", models.TextField()),
                ("task_last_date", models.DateField()),
                ("task_completed_date", models.DateField()),
                (
                    "task_status",
                    models.IntegerField(
                        choices=[(1, "חדש"), (2, "בתהליך"), (3, "הושלם")]
                    ),
                ),
                (
                    "task_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="MyTasks",
                        to="TasksManagementApp.employee",
                    ),
                ),
                (
                    "task_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="TasksManagementApp.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_Team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="TasksManagementApp.team",
            ),
        ),
    ]
