# Generated by Django 5.2.5 on 2026-01-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0003_alter_employee_employee_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_Team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="TasksManagementApp.team",
            ),
        ),
    ]
