# Generated by Django 5.2.5 on 2026-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0004_alter_employee_employee_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "מנהל"), (2, "עובד")], default=2
            ),
        ),
    ]
