# Generated by Django 5.2.6 on 2026-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0005_alter_employee_employee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_completed_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_last_date",
            field=models.DateField(null=True),
        ),
    ]
