# Generated by Django 5.2.6 on 2026-01-08 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0006_alter_task_task_completed_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="MyTasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
