# Generated by Django 5.2.6 on 2026-01-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0007_alter_task_task_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="TasksManagementApp.team",
            ),
        ),
    ]
