# Generated by Django 5.2.6 on 2026-01-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0009_alter_employee_employee_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_Team",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="TasksManagementApp.team",
            ),
        ),
    ]
